### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by COLABORATI** [matagus/django-planet#68]
I see that this seems to be very old and unmaintained code. Is this project dead?

**Comment by matagus** [comment]
It's just a project I'm maintaining in my spare time and with no support, that's why it may seem unmaintained. Also it's open source: if you find an issue you may fix it, open a pull request and I'll be very happy to merge it if it works and pass the tests.

Code is old but it works at least in Django 1.7 and 1.8. There [this pull request](#66) for making templates work in Django 1.9 that I'll be testing tomorrow. 

Thaks for your interest!

**Comment by COLABORATI** [comment]
OK, nice to see that there is some life here, it would be really a pitty when this project was not alive. Happy to see updates!
